function [trq,spd,frct,cur_int] = rw_dynamics(par,voltage,cur_cmd, spd, temp, dt)

persistent cur_motor

% Back EMF Saturation
iemf = (voltage - par.ke*spd)/ par.r_mot;   % [V]
cur_cmd = rw_satcheck(cur_cmd,iemf);

% Internal Current
cur_int   = rw_mdl_cur_int(par, spd, cur_cmd, temp, 0);
% fprintf('Internal Current: %.9f [A] \n',cur_int);
% Actual Current    
cur_motor = cur_cmd + cur_int;

% Friction 
frct = rw_mdl_friction(par, spd, temp, 'pos');

% Actual Torque & Speed 
trq = par.km * cur_motor + frct;   % [Nm] Torque Generated by Current (includes friction effect)
spd = spd + trq/par.J * dt; % [rad/s] wheel speed

% fprintf('Torque: %.9f [Nm]\n',trq);
end